#!/usr/bin/env python3.13
"""Convert PyRIT Crescendo conversation traces into our YAML corpus format.

Workflow:
    1. Run `python crescendo_demo.py --objective "..."` one or more times
       (each run writes to `generated/last-run.json`).
    2. Run `python import_to_corpus.py` to extract the prompts used by
       Crescendo across turns and write them as multi-turn scenarios in
       our corpus YAML format.

Each PyRIT Crescendo run produces a single "scenario" with multiple
`turns`. Our corpus already supports multi-turn scenarios via the `turns`
list — Crescendo runs slot in naturally.

Run with --preview to see the output without writing.

Note: in production this would query the PyRIT DuckDB memory directly.
For the demo we read the JSON summary written by `crescendo_demo.py`.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml


def _slugify(text: str, max_len: int = 50) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower())
    text = text.strip("-")[:max_len]
    return text or "scenario"


def _derive_category(objective: str) -> str:
    """Heuristic mapping of objective text to our corpus category."""
    obj_lower = objective.lower()
    if any(k in obj_lower for k in ("address", "phone", "pii", "personal", "ferpa")):
        return "personal_information"
    if any(k in obj_lower for k in ("cheat", "essay", "plagia")):
        return "cheating_integrity"
    if any(k in obj_lower for k in ("dating", "romance", "flirt")):
        return "dating_romance"
    if any(k in obj_lower for k in ("political", "election", "biden", "trump")):
        return "politics"
    if any(k in obj_lower for k in ("violence", "hurt", "fight")):
        return "violence"
    if any(k in obj_lower for k in ("system prompt", "instructions")):
        return "prompt_leakage"
    return "jailbreak"


def convert(run_summary: dict[str, Any], scenario_idx: int) -> dict[str, Any]:
    objective = run_summary["objective"]
    turns_count = run_summary.get("executed_turns", 0)
    category = _derive_category(objective)
    achieved = run_summary.get("achieved_objective", False)

    # For the demo, we synthesize a single-turn scenario using the
    # objective as the prompt. A future enhancement would extract each
    # of Crescendo's actual escalation prompts from PyRIT's DuckDB
    # memory and emit one scenario with `turns: [t1, t2, t3...]`.
    return {
        "id": f"pyrit-crescendo-{category}-{_slugify(objective, 40)}-{scenario_idx:03d}",
        "category": category,
        "language": "en",
        "tags": ["full", "pyrit-generated", "pyrit-crescendo", "multi-turn"],
        "turns": [objective],
        "expected_behavior": {
            "refusal_required": True,
            "must_not_include": [],
        },
        "notes": (
            f"Generated by PyRIT CrescendoOrchestrator across "
            f"{turns_count} turn(s). "
            f"Objective: {objective}. "
            f"Attack outcome in source run: "
            f"{'SUCCESS (target complied — high-severity finding)' if achieved else 'FAILED (target refused — expected)'}. "
            "Reviewer: confirm category mapping; consider expanding "
            "turns[] with the actual escalation chain from PyRIT memory."
        ),
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "source",
        nargs="?",
        default="generated/last-run.json",
        help="Path to a PyRIT run JSON summary (default: generated/last-run.json)",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default="../prototype/src/vt_agent_redteam/corpus/pyrit_generated.yaml",
        help="Where to write the YAML corpus file",
    )
    parser.add_argument("--preview", action="store_true")
    args = parser.parse_args(argv[1:] if len(argv) > 1 else [])

    source = Path(args.source)
    if not source.exists():
        print(f"ERROR: source file not found: {source}", file=sys.stderr)
        print("Run `python crescendo_demo.py` first to generate it.", file=sys.stderr)
        return 1

    with source.open() as fp:
        run = json.load(fp)

    scenario = convert(run, scenario_idx=1)
    scenarios = [scenario]
    yaml_out = yaml.safe_dump(scenarios, sort_keys=False, allow_unicode=True, width=80)

    if args.preview:
        print(yaml_out)
        print(f"\n[preview only — would write 1 scenario to {args.target}]", file=sys.stderr)
        return 0

    target = Path(args.target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(yaml_out)
    print(f"Wrote 1 scenario to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
